[theme]
primaryColor = "#FFD700"
backgroundColor = "#FFFFE0"
secondaryBackgroundColor = "#FFFACD"
textColor = "#000000"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
